services:
  nano_container:
    container_name: nano
    image: rosmaster/ros2:nano
    runtime: nvidia
    privileged: true
    ipc: host
    tty: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev

    environment:
      - "DISPLAY=$DISPLAY"
      - "DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/udev:/etc/udev
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw